Feat/gelato safety compound
InsureDAO/pool-contracts pull request #203
Opened 2022-09-27 11:40 UTC by maguroid

Enabled safety auto compound using Gelato

2022-09-28 07:27 UTC, oishun1112 requested changes
Please check comments above, and update or give me your thoughts.

2022-09-28 07:27 UTC, oishun1112 commented on contracts/logics/ExchangeLogicUniswapV3.sol
> +    uint256 public immutable slippageTolerance; // 0.3%
This should be "constant" instead of "immutable" when this has to be 0.3% as the comment.

2022-09-28 07:27 UTC, oishun1112 commented on contracts/strategies/AaveV3Strategy.sol
> +    uint256 public minCompoundLimit;
"Limit" means the maximum. so, use something other term.

2022-09-28 07:27 UTC, oishun1112 commented on contracts/strategies/AaveV3Strategy.sol
> +        emit RewardClaimed(address(aaveRewardToken), _claimable);
it is cheaper to emit event at the end of function

2022-09-28 07:27 UTC, oishun1112 commented on contracts/strategies/AaveV3Strategy.sol
> +    uint256 public minCompoundLimit;
This is also misleading since it only applies to check(), not compound().

2022-09-28 07:27 UTC, oishun1112 commented on contracts/strategies/AaveV3Strategy.sol
> +        emit RewardClaimed(address(aaveRewardToken), _claimable);
claimAllRewards will call event "RewardsClaimed", so not necessary to emit event by us.

https://github.com/aave/aave-v3-periphery/blob/c3d745f2aefd7aed04ac520f0132722afbda1587/contracts/rewards/RewardsController.sol#L302

2022-09-28 07:27 UTC, oishun1112 commented on contracts/strategies/AaveV3Strategy.sol
> +        emit RewardClaimed(address(aaveRewardToken), _claimable);
We should use claimRewards rather than claimAllReward, since latter one can claim multiple kind of token rewards that this contract won't recognize.

2022-09-28 08:12 UTC, maguroid commented on contracts/logics/ExchangeLogicUniswapV3.sol
> +    uint256 public immutable slippageTolerance; // 0.3%
I removed the comment and stay it immutable, because we might deploy another instance with different slippage tolerance.

2022-09-28 08:16 UTC, maguroid commented on contracts/strategies/AaveV3Strategy.sol
> +    uint256 public minCompoundLimit;
Changed var name to minOpsTrigger. What do you think?

2022-09-28 08:25 UTC, maguroid commented on contracts/strategies/AaveV3Strategy.sol
> +        emit RewardClaimed(address(aaveRewardToken), _claimable);
got it. fixed like that.

2022-10-11 11:02 UTC, jack-the-pug commented on contracts/strategies/AaveV3Strategy.sol
> +            _execPayload = abi.encodeWithSelector(this.compound.selector);
`_estimatedOutUsdc` should be passed to the `compound()` as part of the calldata for slippage control

2022-10-12 05:59 UTC, maguroid commented on contracts/strategies/AaveV3Strategy.sol
> +            _execPayload = abi.encodeWithSelector(this.compound.selector);
Absolutely. I pushed the new commit.

2022-10-12 07:42 UTC, oishun1112 commented on contracts/strategies/AaveV3Strategy.sol
> +    uint256 public minCompoundLimit;
Yes! that makes sense

2022-10-14 03:58 UTC, merged